[package]
name = "waters"
version = "0.1.0"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/wassasin/waters"
keywords = ["ibe", "encryption", "ecc", "no_std"]
categories = ["cryptography", "no-std"]

[dependencies]
rand = "0.7"
tiny-keccak = "1.5.0"
subtle = "2.1.1"
arrayref = "0.3.5"
bls12_381 = { git = "https://github.com/wassasin/bls12_381", branch = "gt-serialisation" }

[dependencies.byteorder]
version = "1"
default-features = false

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "main"
harness = false