[package]
name = "waters"
version = "0.1.0"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"

[dependencies]
rand = "0.4"
tiny-keccak = "1.5.0"
pairing = { version = "0.14.2", features = ["expose-arith"] }